server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clashDb
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
#  profiles:
#    active: dev

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

logging:
  level:
    com:
      args:
        brtravels:
          clients:
            clash:
              ClashClient: DEBUG

clash:
  apiKey: ${API_KEY_CLASH_CLIENT}
  baseUrl: ${BASE_URL_CLASH_CLIENT}
  clientName: ${CLIENT_NAME_CLASH_CLIENT}
mailgun:
  apiKey: ${API_KEY_MAILGUN_CLIENT}
  baseUrl: ${BASE_URL_MAILGUN_CLIENT}
  clientName: ${CLIENT_NAME_MAILGUN_CLIENT}